### PR TITLE
Rc 

### PR DESCRIPTION
**Pull request by dtan**
Hey Dav,
I added a few things - -t/--themedir flag, fixed the -x flag (it was referencing options.extension instead of options.exclude) as well as the README.md (sorry for all the commits on that file, i don't know how to test the markdown prior to pushing).

let me know if this is the appropriate workflow for sending you pull requests.

thanks
dale

### CODE REVIEW

**Comment by davglass** [comment]
Sorry, I didn't see this request and it's not a clean merge.. Can you update your fork with the latest and fix the merge?

**Comment by dtan** [comment]
sure no problem.  was wondering if they got to you or not =).  I'll send
another once everything is ready.

On Mon, Jun 27, 2011 at 11:26 AM, davglass <
reply@reply.github.com>wrote:

> Sorry, I didn't see this request and it's not a clean merge.. Can you
> update your fork with the latest and fix the merge?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davglass/yuidocjs/pull/5#issuecomment-1448069

## 

## 

CONFIDENTIALITY NOTICE: This e-mail transmission, and any documents,
files or previous e-mail messages attached to it may contain confidential
information that is legally privileged and is intended for the designated
recipient only. If you have received it in error, please notify the sender
immediately and delete the original. Any other use of the email by you is
STRICTLY PROHIBITED.

**Comment by davglass** [comment]
I will be doing some work on this today, so let me know before you land it so I can merge it properly..

**Comment by dtan** [comment]
ok thanks for the heads up.  I will probably work on it later today since
something at work just came up.  Do i just a git pull on my origin master
branch to get your updated files?

On Mon, Jun 27, 2011 at 12:03 PM, davglass <
reply@reply.github.com>wrote:

> I will be doing some work on this today, so let me know before you land it
> so I can merge it properly..
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davglass/yuidocjs/pull/5#issuecomment-1448344

## 

## 

CONFIDENTIALITY NOTICE: This e-mail transmission, and any documents,
files or previous e-mail messages attached to it may contain confidential
information that is legally privileged and is intended for the designated
recipient only. If you have received it in error, please notify the sender
immediately and delete the original. Any other use of the email by you is
STRICTLY PROHIBITED.

**Comment by davglass** [comment]
You need to add mine as an upstream, pull my changes then merge yours:

http://help.github.com/fork-a-repo/

**Comment by dtan** [comment]
hey dav,
do you know what was in conflict?  I just merged the your upstream to my rc branch and the only conflict i got was with the themes/default/assets/js/tabs.js file.  Everything else merged fine into my rc branch.

**Comment by davglass** [comment]
I just noticed the conflict shown here that the pull request could not be automatically merged. So I ignored it..

**Comment by dtan** [comment]
ok, i fixed and pushed my git conflict (hopefully).  please have another look.

thanks
dale

**Pull request merged**
