### PR TITLE
Added detailed descriptions for all primary tags.

### PR DESCRIPTION
**Pull request by evangoer**
Also moved @attribute into the primary tag list.

### CODE REVIEW

**Comment by davglass** [comment]
Dude, you rock!

**Comment by evangoer** [comment]
Thanks!

This looks like a light day -- meetings cancelled and no SNV tech talk. So if you don't have any objections, I'll try to see how far I get on this today.

**Comment by davglass** [comment]
Kewl, I won't merge it in until you give me the ok then ;)

**Comment by evangoer** [comment]
Okay, it's ready for examination & merging. 

Tomorrow if I have time I'd like to glue the various tiny user guides relating to running the yuidoc command line tool into a single user guide. Ideally I think the project should start with:
- main page
- Running yuidoc
- YUIDoc Comment Syntax

Then later add bonus material -- style guide, detailed examples, etc.

**Pull request merged**
